import type { NextPage } from 'next';
import Head from 'next/head';

import Snackbar from '@/ui/components/snackbar';
import HomePage from '@/ui/views/home';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
      <Snackbar />
    </>
  );
};

export default Home;
