import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../ui/styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.root}>Hello</div>
    </>
  );
};

export default Home;
